cloud:
  aws:
    region:
      static: AWS_REGION
    s3:
      bucket: BUKET_NAME
    credentials:
      access-key: ACCESS KEY
      secret-key: SECRET KEY
    stack:
      auto: false
 
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR